### PR TITLE
fix: implement domain pattern matching for auto-translation configuration

### LINKED ISSUE #699: URL匹配规则过于宽泛，导致在非目标域名错误激活
- 设定为在访问 `x.com` 时自动翻译。
- 插件在非目标域名如 `ax.com` `bbx.com` `cccx.com`上意外激活。

示例链接：
https://www.google.com/search?q=x.com
https://argenx.com/

### PR DESCRIPTION
**Pull request by lisongkun**
## Type of Changes

- [ ] ✨ New feature (feat)
- [x] 🐛 Bug fix (fix)
- [ ] 📝 Documentation change (docs)
- [ ] 💄 UI/style change (style)
- [ ] ♻️ Code refactoring (refactor)
- [ ] ⚡ Performance improvement (perf)
- [ ] ✅ Test related (test)
- [ ] 🔧 Build or dependencies update (build)
- [ ] 🔄 CI/CD related (ci)
- [ ] 🌐 Internationalization (i18n)
- [ ] 🧠 AI model related (ai)
- [ ] 🔄 Revert a previous commit (revert)
- [ ] 📦 Other changes that do not modify src or test files (chore)

## Related Issue

Closes #699 

## How Has This Been Tested?

- [ ] Added unit tests
- [x] Verified through manual testing

## Checklist

- [x] I have tested these changes locally
- [x] I have updated the documentation accordingly if necessary
- [x] My code follows the code style of this project
- [x] My changes do not break existing functionality
- [x] If my code was generated by AI, I have proofread and improved it as necessary.

## Additional Information

---
## Summary by cubic
Adds precise domain pattern matching for auto-translation, matching exact domains and subdomains only. Validates URLs and ignores invalid ones, fixing false positives from substring checks (e.g., x.com no longer matches ax.com).

- **Bug Fixes**
  - Introduced matchDomainPattern with exact/subdomain logic and strict URL validation (zod), returning false for invalid URLs.
  - Replaced naive includes checks in getIsInPatterns, toggleCurrentSiteAtom, and shouldEnableAutoTranslation with the new matcher; added unit tests; addresses #699.

<sup>Written for commit c57c049ec33852d1ff0874c44c6cab9cf1d136a1. Summary will update automatically on new commits.</sup>

### CODE REVIEW

File: src/utils/host/translate/auto-translation.ts [hunk 1]
```diff
@@ -1,13 +1,59 @@
 import type { Config } from '@/types/config/config'
 import { getFinalSourceCode } from '@/utils/config/languages'
 
+/**
```
Comment (mengxi-ream) [inline src/utils/host/translate/auto-translation.ts]: 1. we don't like comment in code, because we believe good code explain themselves and self-documented
2. If you feel we have to add the comment somewhere, use English please

File: src/utils/host/translate/auto-translation.ts [hunk 2]
```diff
@@ -1,13 +1,59 @@
...
+ * 精确匹配域名模式
+ * 支持完全匹配和子域名匹配，但不匹配包含该模式的其他域名
+ * @param url - 要检查的 URL
+ * @param pattern - 域名模式（如 "x.com"）
+ * @returns 是否匹配
+ */
+export function matchDomainPattern(url: string, pattern: string): boolean {
```
Comment (mengxi-ream) [inline src/utils/host/translate/auto-translation.ts:6]: Could you write some tests for this function?

File: src/utils/host/translate/auto-translation.ts [hunk 3]
```diff
@@ -1,13 +1,59 @@
...
+    // 子域名匹配：hostname 以 "." + pattern 结尾
+    // 例如：pattern = "x.com"，匹配 "www.x.com"、"sub.x.com"
+    // 但不匹配 "ax.com"、"bbx.com"
+    if (hostname.endsWith(`.${patternLower}`)) {
+      return true
+    }
+
+    return false
+  }
+  catch {
```
Comment (mengxi-ream) [inline src/utils/host/translate/auto-translation.ts]: AI like `try catch` but human don't. In logic, if the `new URL()` fails, you shouldn't assume we want to match `urlLower` with `pattern`, this is just one posibility, there are a lot other cases.

What you should do is to use `zod` to validate `url` string at the beginning of this function, if validation result is false, return false. then this function becomes "only return true when url is valid url and match the pattern", which is a very clear purpose.

The current try catch logic makes this function dirty and not clear with it's real purpose.

**Comment by mengxi-ream** [comment]
this PR should be a "fix" patch.

**Comment by lisongkun** [comment]
I'll review all  your comments later, Thanks for your patience
