### PR TITLE
fix: reinsert when an internal node is removed

### LINKED ISSUE #410: [BUG] 网站通过 url 锚点改变内容（即单页应用）点击改变锚点的链接时，侧边栏会弹出来
### Before you report

- [x] I have searched existing issues to avoid duplicates
- [x] I have tried with the latest available version (or can reproduce on latest)

### Current vs. Expected behavior

点击导航链接时，侧边栏弹出，而且没法点击关闭按钮关掉侧边栏

### To Reproduce

如： https://docs.basedpyright.com/v1.29.4/benefits-over-pyright/new-diagnostic-rules/
点击左侧导航链接，侧边栏就会弹出

### Which area(s) are affected? (Select all that apply)

Browser Extension

### Extension version (if applicable)

1.0.0 ~ 1.5.4

### Provide environment information

```bash
- Edge ：  139.0.3405.119
- Windows 11
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by taiiiyang**
## Type of Changes

- [ ] ✨ New feature (feat)
- [x] 🐛 Bug fix (fix)
- [ ] 📝 Documentation change (docs)
- [ ] 💄 UI/style change (style)
- [ ] ♻️ Code refactoring (refactor)
- [ ] ⚡ Performance improvement (perf)
- [ ] ✅ Test related (test)
- [ ] 🔧 Build or dependencies update (build)
- [ ] 🔄 CI/CD related (ci)
- [ ] 🌐 Internationalization (i18n)
- [ ] 🧠 AI model related (ai)
- [ ] 🔄 Revert a previous commit (revert)
- [ ] 📦 Other changes that do not modify src or test files (chore)

## Description

 reinsert when an internal node is removed in side.content

## Related Issue

Closes #410 #170 

## How Has This Been Tested?

- [ ] Added unit tests
- [x] Verified through manual testing

## Checklist

- [x] I have tested these changes locally
- [x] I have updated the documentation accordingly if necessary
- [x] My code follows the code style of this project
- [x] My changes do not break existing functionality
- [x] If my code was generated by AI, I have proofread and improved it as necessary.

## Additional Information

    

---

## Summary by cubic
Prevents style loss when internal extension style nodes are removed by reinserting them, fixing side content auto-expand styling issues.

- **Bug Fixes**
  - Detects extension-owned style nodes (wxt shadow styles, _goober, sonner toaster) with a new isInnerDom check.
  - On DOM changes, reattaches any removed internal nodes to document.head within mirrorDynamicStyles.

### CODE REVIEW

File: apps/extension/src/utils/styles.ts [hunk 1]
```diff
@@ -15,6 +15,25 @@ export function addStyleToShadow(shadow: ShadowRoot) {
...
+
+  if (node instanceof HTMLStyleElement && node.attributes.getNamedItem('wxt-shadow-root-document-styles')) {
+    return true
+  }
+
+  if (node instanceof HTMLStyleElement && node.id === '_goober') {
+    return true
+  }
+
+  if (node.textContent?.includes('[data-sonner-toaster]')) {
```
Comment (mengxi-ream) [inline apps/extension/src/utils/styles.ts]: this function looks like hard coding the conditions. what if in the future we add other style elements? or we delete some styles?

We may need a systematically way. to let this function can dynamically detect all css we insert. i.e., when we insert a new style into dom in the future, we don't need to change any code in this function, and that will be automatically watched by `mutation.removedNodes`

One idea I have is to add the special `id` like `read-frog-insert-style` to every css we insert and this function can only detect that `id`, if the style has that `id` then return `true`

But there might be a better idea you can come up with. the above one just give you an example that what we want.

**Review by mengxi-ream — CHANGES_REQUESTED** [review]
have we tested this on another similar issue as well? https://github.com/mengxi-ream/read-frog/issues/170

**Comment by taiiiyang** [comment]
> have we tested this on another similar issue as well? #170

yes, no problem

File: apps/extension/src/utils/styles.ts (hunk 1 above)
Comment (taiiiyang) [reply apps/extension/src/utils/styles.ts]: I have also considered this issue, but these styles are all injected by wxt and sonner. I don't know where to uniformly intercept them.

Comment (mengxi-ream) [reply apps/extension/src/utils/styles.ts]: If you don't feel there is a very good way to do. Maybe just leave it as this. But I'm not sure why we use the name "innerXXX" as the function name

Comment (taiiiyang) [reply apps/extension/src/utils/styles.ts]: > If you don't feel there is a very good way to do. Maybe just leave it as this. But I'm not sure why we use the name "innerXXX" as the function name

Used to determine if it is a DOM injected internally by read frog. Can you provide a better example?

Comment (taiiiyang) [reply apps/extension/src/utils/styles.ts]: > If you don't feel there is a very good way to do. Maybe just leave it as this. But I'm not sure why we use the name "innerXXX" as the function name

Can I use `isInternalStyleElement` ?
