### PR TITLE
fix: fix the thought process in the translation of the custom model.

### LINKED ISSUE #705: Show the thinking when translating
image

### PR DESCRIPTION
**Pull request by Yukiniro**
## Type of Changes

- [ ] ✨ New feature (feat)
- [x] 🐛 Bug fix (fix)
- [ ] 📝 Documentation change (docs)
- [ ] 💄 UI/style change (style)
- [ ] ♻️ Code refactoring (refactor)
- [ ] ⚡ Performance improvement (perf)
- [ ] ✅ Test related (test)
- [ ] 🔧 Build or dependencies update (build)
- [ ] 🔄 CI/CD related (ci)
- [ ] 🌐 Internationalization (i18n)
- [ ] 🧠 AI model related (ai)
- [ ] 🔄 Revert a previous commit (revert)
- [ ] 📦 Other changes that do not modify src or test files (chore)

## Related Issue

Closes #705 #674

## How Has This Been Tested?

- [ ] Added unit tests
- [x] Verified through manual testing

## Checklist

- [x] I have tested these changes locally
- [ ] I have updated the documentation accordingly if necessary
- [x] My code follows the code style of this project
- [ ] My changes do not break existing functionality
- [ ] If my code was generated by AI, I have proofread and improved it as necessary.

## Additional Information

---
## Summary by cubic
Fixed the translation thought process for custom models by applying provider-specific options and disabling thinking for GLM models. This makes translations consistent and prevents unintended reasoning steps.

- **Bug Fixes**
  - Added model-specific options in getProviderOptions (GLM-* sets thinking to disabled).
  - getProviderOptions now accepts providerName and applies options to the correct provider.
  - Passed providerName through translate, language detection, and summary flows so custom model settings are honored.

<sup>Written for commit 5594d7f158208d113062d675829e0ee3c4f70313. Summary will update automatically on new commits.</sup>

### CODE REVIEW

File: src/utils/constants/model.ts [hunk 1]
```diff
@@ -6,8 +6,24 @@ import { THINKING_MODELS } from '@/types/config/provider'
...
+ * Used to apply special configurations for certain models that need custom behavior.
+ */
+const MODEL_SPECIFIC_OPTIONS: Array<{
+  pattern: RegExp
+  options: Record<string, JSONValue>
+}> = [
+  {
+    // GLM models have issues with thinking mode, causing errors or unexpected behavior
+    // Disable thinking for all GLM-* models (case-insensitive)
+    pattern: /^GLM-/i,
```
Comment (mengxi-ream) [inline src/utils/constants/model.ts:20]: have you test if all GLM models accept `{ thinking: { type: 'disabled' } }` without error return?

could you test this on some non-thinking GLM models and check if this will break them?

Comment (Yukiniro) [reply src/utils/constants/model.ts:20]: Models of GLM-4.5 and above support [Thinking](https://docs.bigmodel.cn/api-reference/%E6%A8%A1%E5%9E%8B-api/%E5%AF%B9%E8%AF%9D%E8%A1%A5%E5%85%A8); I tried GLM-4 and it worked without any problems.

**Review by mengxi-ream — APPROVED** [review]
