### PR TITLE
fix: flicker of the always translate switch

### LINKED ISSUE #123: [BUG] should use hydration atom to allow load state before the first paint of popup page
**Describe the bug**

should use hydration atom to allow load state before the first paint of popup page

now, it will load as `False` and then switch to the correct state after the first paint

**To Reproduce**

https://github.com/user-attachments/assets/f6e34623-7030-447c-a301-edf3d4fea2a7

**Expected behavior**

should worked like `Show floating button` switch state

### PR DESCRIPTION
**Pull request by taiiiyang**
## Type of Changes

- [ ] ✨ New feature (feat)
- [x] 🐛 Bug fix (fix)
- [ ] 📝 Documentation change (docs)
- [ ] 💄 UI/style change (style)
- [ ] ♻️ Code refactoring (refactor)
- [ ] ⚡ Performance improvement (perf)
- [ ] ✅ Test related (test)
- [ ] 🔧 Build or dependencies update (build)
- [ ] 🔄 CI/CD related (ci)
- [ ] 🌐 Internationalization (i18n)
- [ ] 🧠 AI model related (ai)
- [ ] 🔄 Revert a previous commit (revert)
- [ ] 📦 Other changes that do not modify src or test files (chore)

## Description

use hydration atom to allow load state before the first paint of popup page

## Related Issue

[https://github.com/mengxi-ream/read-frog/issues/123](https://github.com/mengxi-ream/read-frog/issues/123)

close #123
## How Has This Been Tested?

- [ ] Added unit tests
- [x] Verified through manual testing

## Checklist

- [x] I have tested these changes locally
- [x] I have updated the documentation accordingly if necessary
- [x] My code follows the code style of this project
- [x] My changes do not break existing functionality
- [x] If my code was generated by AI, I have proofread and improved it as necessary.

### CODE REVIEW

File: src/entrypoints/popup/atom.ts [hunk 1]
```diff
@@ -44,6 +45,15 @@ export const initIsIgnoreTabAtom = atom(null, async (get, set) => {
 // Sync atom to store the checked state
 export const isCurrentSiteInPatternsAtom = atom<boolean>(false)
 
+export function initIsInPatterns(config: Config, activeTabUrl: string) {
```
Comment (mengxi-ream) [inline src/entrypoints/popup/atom.ts]: duplicated code as in `initIsCurrentSiteInPatternsAtom`, extract the logic

File: src/entrypoints/popup/main.tsx [hunk 2]
```diff
@@ -37,13 +39,15 @@ function HydrateAtoms({
 async function initApp() {
   const root = document.getElementById('root')!
   root.className = 'text-base antialiased w-[320px] bg-background'
-  const config = await storage.getItem<Config>('local:config')
+  const config = await storage.getItem<Config>('local:config') ?? DEFAULT_CONFIG
```
Comment (mengxi-ream) [inline src/entrypoints/popup/main.tsx]: acutally should use globalConfig here, which resolve the load and init issue for config

**Review by mengxi-ream — CHANGES_REQUESTED** [review]
add `close #xxxx` to close the issue automatically after merging
