### PR TITLE
fix: sync provider options editor when switching providers

### LINKED ISSUE #994: [BUG] 不同的提供商错误的共享相同的提供商选项
### Before you report

- [x] I have searched existing issues to avoid duplicates
- [x] I have tried with the latest available version (or can reproduce on latest)

### Current vs. Expected behavior

https://github.com/user-attachments/assets/f21289b2-7ed5-404f-8056-c4b910dd31ac

### To Reproduce

见视频

### Which area(s) are affected? (Select all that apply)

Browser Extension

### Extension version (if applicable)

1.25.1

### Provide environment information

```bash
- OS: Windows 11
- Browser: Edge 145
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by cesaryuan**
## Type of Changes
- [x] 🐛 Bug fix (fix)

## Description
Fix provider options editor state leakage when switching between different providers.
The editor previously kept local JSON input from the previous provider and could submit it to the newly selected provider.

## Related Issue
Closes #994

## How Has This Been Tested?
- [ ] Added unit tests
- [x] Verified through manual testing

Manual steps:
1. Open API Providers page
2. Select Provider A and input provider options JSON
3. Switch to Provider B
4. Confirm Provider B shows its own options (or empty/default), not Provider A's stale JSON
5. Switch back and forth to verify isolation

Local checks run:
- `pnpm lint`
- `pnpm type-check`
- `pnpm build`
- `pnpm test`

## Checklist
- [x] I have tested these changes locally
- [x] My code follows the code style of this project
- [x] My changes do not break existing functionality

---
## Summary by cubic
Fixes stale JSON in the provider options editor when switching providers. The editor now resets to the selected provider’s options (or empty) to prevent submitting data from the previous provider.

- **Bug Fixes**
  - Sync the editor on provider change using useEffectEvent keyed by providerConfig.id, re-initializing from the current provider’s options.

<sup>Written for commit e41b0d68d7bef82a916e0fbfe7f57510aa00c308. Summary will update on new commits.</sup>

### CODE REVIEW

File: src/entrypoints/options/pages/api-providers/provider-config-form/provider-options-field.tsx [hunk 1]
```diff
@@ -30,11 +30,18 @@ export const ProviderOptionsField = withForm({
...
+        ? JSON.stringify(providerConfig.providerOptions, null, 2)
+        : ''
+    ), [providerConfig.providerOptions])
     const [jsonInput, setJsonInput] = useState(initialValue)
 
+    // Keep editor input in sync when switching to a different provider config.
+    useEffect(() => {
+      setJsonInput(initialValue)
+    }, [providerConfig.id, initialValue])
+
```
Comment (mengxi-ream) [inline src/entrypoints/options/pages/api-providers/provider-config-form/provider-options-field.tsx]: the useMemo depends on providerOpotions is not right, because 
- the useEffect depends on initialValue
- initialValue depends on providerOptions

so when you change providerOptions in the setting, you trigger the initialValue to change and the jsonInput to change. which is an extra rendering and may cause unexpected UI flicking.

better idea is:

```tsx
const toJson = (options: APIProviderConfig['providerOptions']) =>
    options ? JSON.stringify(options, null, 2) : ''

const [jsonInput, setJsonInput] = useState(() => toJson(providerConfig.providerOptions))

useEffect(() => {
    setJsonInput(toJson(providerConfig.providerOptions))
  }, [providerConfig.id])
```

**Review by mengxi-ream — APPROVED** [review]

**Review by mengxi-ream — APPROVED** [review]
